spring.application.name=BookMyShow
server.port=8080


# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=bookmyshowApp


# ===============================
#  MySQL Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/BookmyshowApp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rohan@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SendGrid SMTP Configuration

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# PayPal Configuration

paypal.client.id=Ae1F-GXiS_CWsBk6l28NDEbYaRKjLkjgu7xxpllERaJ55kM7CXpZY0t8nvZtR8WinNBKZMQrmPPRuazk
paypal.client.secret=ENig0h4X_6_eSjXoMag4UEIOO4kvduSZVimrNxA1nnLqfPoyEgcF6IvMj-4MpgWq6eHSTHPtMu7aLCFi
paypal.mode=sandbox

spring.redis.host=localhost
spring.redis.port=6379
# ===============================
# Logging (Optional but useful)
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
